### ISSUE TITLE
User Input: "per week / per month / per year"

### ISSUE THREAD

**Issue by GN101** [GN101/consumerism_app#30]
User needs to have a choice between "per week / per month / per year" when submitting his input, per individual input.
This makes sense because some inputs are counted on a weekly / month basis (e.g. `groceries`) while others are counted on a annual basis (e.g. `trips`, `clothes` etc).

- [x]  when input field is focused, said div should appear below the label.
- [x] it's default value should be `per month`
- [x] upon clicking a choice, it should slide down and be hidden and a related text should appear next to the input field (e.g. ______ "per month")
- [x]  on form submit, we must calculate the user input for all possible categories (per week / per month / per year). e.g. a total sum of 100/month equals 25/week and 1200/year.
- [ ]  BONUS: we could store user's preference for any future usage (= re-submitting / updating his user values)

**Comment by miskas9** [comment]
Time Categorisation form doesn't appear if you use Tab instead of clicking to navigate.
